name: Create Release Cycle pull request
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  releasePromotion:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Extract branch name on pull request
        id: extract_branch
        run: echo "::set-output name=current_branch::$(echo ${GITHUB_HEAD_REF})"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: Get latest Release
        id: latest_release
        run: |
          LATEST_RC=$(git for-each-ref --format="%(refname)|%(contents)" --sort=-creatordate --count=2  "refs/tags/rc-*" | head -1 | tail -1)
          echo ::set-output name=current_release::$(echo $LATEST_RC | awk -F ' '  '{print $NF}')
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest_release.outputs.current_release }}
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.extract_branch.outputs.current_branch }}
